#config_version=5

mode:
  start_events: start_gym2_event
  restart_on_next_ball: true
  stop_events: stop_gym2_event 
  events_when_started:
  events_when_stopped:
  priority: 203 

slides:
  slide_mode_gym2_started:
    widgets:
      - type: text
        text: GYM 2
        number_grouping: true
        min_digits: 2
        font_size: 100
        y: 60
        x: 10
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: SAUCER (gym2_saucer)/3
        number_grouping: true
        min_digits: 2
        font_size: 50
        anchor_x: left
        anchor_y: bottom
        y: 10
        x: 10
  
slide_player:
  mode_gym2_started:
    slide_mode_gym2_started:
      target: middle   



variable_player:
  s_saucer_active:
    gym2_saucer: 1

event_player:
  check_gym2_saucer{current_player.gym2_saucer >= 3}:
    - stop_gym2_event


  s_saucer_active:
    check_gym2_saucer
